---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 172.16.116.20
        k8s-1:
          ansible_host: 172.16.116.21
        k8s-2:
          ansible_host: 172.16.116.22
    worker:
      hosts:
        k8s-3:
          ansible_host: 172.16.116.23
        k8s-4:
          ansible_host: 172.16.116.24
        k8s-5:
          ansible_host: 172.16.116.25
