---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_ADDR: "172.16.116.254"
  METALLB_LB_RANGE: "172.16.116.30-172.16.116.39"
  METALLB_K8S_GATEWAY_ADDR: "172.16.116.30"
  METALLB_INGRESS_ADDR: "172.16.116.31"
